create database customer_analysis;
use customer_analysis;
show tables;
select * from customer_analysis;
rename table customer_analysis to customer_data;
desc customer_data;
select customer_id,gender, category from customer_data;
select * from customer_data where gender = "female";
select * from customer_data where purchase_amount_usd > 50;
select customer_id, category, shipping_type from customer_data order by size asc;
select count(*) as total_customers from customer_data;
select count(*) as female_customers from customer_data where gender = "female";
select sum(previous_purchases) as previous_purchases from customer_data;
select avg(purchase_amount_usd) as purchase_amount from customer_data;
SELECT gender, COUNT(*) AS total FROM customer_data GROUP BY gender;
SELECT category,SUM(purchase_amount_usd) AS total_sales FROM customer_data GROUP BY category;
SELECT category, SUM(purchase_amount_usd) AS total_sales FROM customer_data GROUP BY category HAVING total_sales > 5000;
SELECT category, SUM(purchase_amount_usd) AS total_sales FROM customer_data GROUP BY category ORDER BY total_sales DESC;
SELECT customer_id, SUM(purchase_amount_usd) AS total_spent FROM customer_data GROUP BY customer_id ORDER BY total_spent DESC;